### PR TITLE
Ported Nexus As README

### PR DESCRIPTION
**Pull request by ElectronicsArchiver**
[Badge Suggestions]: https://img.shields.io/badge/Ｒｅｐｏｓｉｔｏｒｙ_Ｓｕｇｇｅｓｔｉｏｎｓ-609926?style=for-the-badge&logoColor=white&logo=GitHub
[Badge Changes]: https://img.shields.io/badge/Ｃｈａｎｇｅｓ-D81939?style=for-the-badge&logoColor=white&logo=GitLFS
[Badge Robot]: https://img.shields.io/badge/Ｉ＇ｍ_Ｈｕｍａｎ-c84f8c?style=for-the-badge&logoColor=white&logo=RuboCop
[Badge Ask]: https://img.shields.io/badge/Ｐｌｅａｓｅ_Ａｓｋ_Ｍｅ-73398D?style=for-the-badge&logoColor=white&logo=AskUbuntu

[License Badges]: https://github.com/MarkedDown/Licenses
[Widgets]: https://github.com/MarkedDown/Disable/blob/main/Features/Widgets.md
[Tabs]: https://github.com/MarkedDown/Disable/blob/main/Features/Tabs.md
[Wiki]: https://github.com/MarkedDown/Wiki

<br>
<br>

<div align = center>

[<kbd> <br> Please Check The **Preview** <br> </kbd>][Preview]

</div>
  
<br>
<br>

## ![Badge Suggestions]

  <br>

- **Add Tags**

  - `skyrim`
  - `mod`
  - `companion`
  - `follower`

  <br>

- **Update Description**

  `Merlin the magical corgi companion.`

  <br>

- **Choose An Actual License**

  **⤷** *https://choosealicense.com/licenses/*
  
  **⤷** **[License Badges]**

  <br>

- ***[Disable unused Tabs][Tabs]***:

  - `Projects`

  - `Actions`

  - `Wiki`
  
  <br>

<br>
<br>

## ![Badge Changes]

- Ported NexusMods page

- Added quicklinks

- Removed non-license

  *Please choose an actual license, link above*

- Added licensing info section

<br>
<br>

## ![Badge Ask]

- ***If you have any questions.***

- ***In case you do not agree with some of the changes made in this PR***, <br>
  *please first let me know about them, before disregarding it entirely so*<br>
  *we can possibly find a middle ground and have it not go to waste.*

<br>
<br>

## ![Badge Robot]

<kbd> <br>            No, I'm not a robot.            <br> </kbd>

<kbd> <br>    Yes, you are not the first.    <br> </kbd>

<kbd> <br>     I just made a PR template.     <br> </kbd>

<br>
<br>

[Preview]: https://github.com/ElectronicsArchiver/Merlin-the-Corgi

### CODE REVIEW

**Comment by ElectronicsArchiver** [comment]
@TateTaylorOH Please review this PR

**Comment by TateTaylorOH** [comment]
My documentation is hosted on the linked Nexus page, this is an source archive. I used to keep documentation on GitHub and Nexus but it became too cumbersome to maintain. I moved everything to Nexus so I didn't need to continue duping information.

I appreciate the offer, but anyone that is interested in the project can read the documentation on Nexus then come here to fork the code.

**Comment by ElectronicsArchiver** [comment]
Well considering that the mod won't change much - I presume -
and I already did the work, why not just accept it?

**Comment by ElectronicsArchiver** [comment]
Also if you want to update it in the future,
you could just ask me and I could write it up~

**Pull request closed without merging**
